numpy library

In [ ]:
print("hello")

hello


In [ ]:
a = 2
b = 3
print('the value of a='+str(a))

the value of a=2


In [ ]:
type(a)
s1="rj college"
type(s1)


str

In [ ]:
a=2.14
type(a)


float

https://numpy.org/doc/stable/user/whatisnumpy.html

In [ ]:
a=[1,2,3]
a

[1, 2, 3]

In [ ]:
type(a)

list

In [ ]:
b=[4,5,6]
b

[4, 5, 6]

In [ ]:
import time
print("sleeping")
time.sleep(30)
print("done sleeping")

sleeping
done sleeping


In [ ]:
import numpy as np
a=np.arange(15).reshape(5,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b=np.array([[12,13,14],[15,16,17]])
b


array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
c=b.reshape(3,2)
c

array([[12, 13],
       [14, 15],
       [16, 17]])

In [ ]:
e=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')