In [ ]:
import numpy
numpy.__version__

'1.19.5'

In [ ]:
list1=[]
list1

[]

In [ ]:
type(list1)

list

In [ ]:
list2=list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list3=[str(c) for c in list2 ]
list3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
list4=[1,10.2,'amit',True]
list4

[1, 10.2, 'amit', True]

In [ ]:
type(list4)

list

In [ ]:
[type(item) for item in list4]

[int, float, str, bool]

In [ ]:
import array as ar
L=list(range(10))
A=ar.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([1,2,3,4] ,dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#[[, ,],[, ,],[, ,]]
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,5),dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((2,6),3.0)

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,4))

array([[0.52263332, 0.890101  , 0.92250743, 0.64289622],
       [0.45912331, 0.91781475, 0.57346457, 0.81707904],
       [0.12128428, 0.45308912, 0.91862369, 0.73383162]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[-0.14109796, -0.38598013,  0.24503525],
       [-0.93858023,  0.55264665, -0.4470895 ],
       [-0.25011943,  1.27831894, -1.58779839]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[7, 2, 1],
       [8, 1, 7],
       [7, 6, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
np.random.seed(100)
x2 = np.random.randint(200, size=(5,6,7))
x2


array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [ ]:
np.random.seed(100)
x2 = np.random.randint(200, size=(5,6,7))
x2


array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [ ]:
x2.shape

(5, 6, 7)

In [ ]:
x2.ndim

3

In [ ]:
x2.size

210

In [ ]:
x2.nbytes

1680

In [ ]:
x2.itemsize

8